name: ecommerce_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  provider: ^6.1.0
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/plus-jakarta-sans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/plus-jakarta-sans/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/plus-jakarta-sans/PlusJakartaSans-Bold.ttf
          weight: 700
